<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tipocontrato', 'doctrine');

/**
 * BaseTipocontrato
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tipocontrato
 * @property decimal $valoradesao
 * @property decimal $valormanutencao
 * @property decimal $valorpontoadcional
 * @property string $quantidadecanais
 * @property string $controlecusto
 * 
 * @method string       getTipocontrato()       Returns the current record's "tipocontrato" value
 * @method decimal      getValoradesao()        Returns the current record's "valoradesao" value
 * @method decimal      getValormanutencao()    Returns the current record's "valormanutencao" value
 * @method decimal      getValorpontoadcional() Returns the current record's "valorpontoadcional" value
 * @method string       getQuantidadecanais()   Returns the current record's "quantidadecanais" value
 * @method string       getControlecusto()      Returns the current record's "controlecusto" value
 * @method Tipocontrato setTipocontrato()       Sets the current record's "tipocontrato" value
 * @method Tipocontrato setValoradesao()        Sets the current record's "valoradesao" value
 * @method Tipocontrato setValormanutencao()    Sets the current record's "valormanutencao" value
 * @method Tipocontrato setValorpontoadcional() Sets the current record's "valorpontoadcional" value
 * @method Tipocontrato setQuantidadecanais()   Sets the current record's "quantidadecanais" value
 * @method Tipocontrato setControlecusto()      Sets the current record's "controlecusto" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTipocontrato extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipocontrato');
        $this->hasColumn('tipocontrato', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '60',
             ));
        $this->hasColumn('valoradesao', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('valormanutencao', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('valorpontoadcional', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('quantidadecanais', 'string', 9, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '9',
             ));
        $this->hasColumn('controlecusto', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '90',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}