<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuarios', 'doctrine');

/**
 * BaseUsuarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $senha
 * @property integer $administrador
 * @property string $nome
 * 
 * @method string   getSenha()         Returns the current record's "senha" value
 * @method integer  getAdministrador() Returns the current record's "administrador" value
 * @method string   getNome()          Returns the current record's "nome" value
 * @method Usuarios setSenha()         Sets the current record's "senha" value
 * @method Usuarios setAdministrador() Sets the current record's "administrador" value
 * @method Usuarios setNome()          Sets the current record's "nome" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsuarios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuarios');
        $this->hasColumn('senha', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('administrador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('nome', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '60',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}