<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vendedor', 'doctrine');

/**
 * BaseVendedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codigo
 * @property string $nome
 * @property integer $comissao
 * 
 * @method string   getCodigo()   Returns the current record's "codigo" value
 * @method string   getNome()     Returns the current record's "nome" value
 * @method integer  getComissao() Returns the current record's "comissao" value
 * @method Vendedor setCodigo()   Sets the current record's "codigo" value
 * @method Vendedor setNome()     Sets the current record's "nome" value
 * @method Vendedor setComissao() Sets the current record's "comissao" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVendedor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vendedor');
        $this->hasColumn('codigo', 'string', 9, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '9',
             ));
        $this->hasColumn('nome', 'string', 105, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '105',
             ));
        $this->hasColumn('comissao', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}