<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Servicosos', 'doctrine');

/**
 * BaseServicosos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $numeroos
 * @property string $descricao
 * @property decimal $valor
 * @property string $caixa
 * @property string $contasreceber
 * 
 * @method string     getNumeroos()      Returns the current record's "numeroos" value
 * @method string     getDescricao()     Returns the current record's "descricao" value
 * @method decimal    getValor()         Returns the current record's "valor" value
 * @method string     getCaixa()         Returns the current record's "caixa" value
 * @method string     getContasreceber() Returns the current record's "contasreceber" value
 * @method Servicosos setNumeroos()      Sets the current record's "numeroos" value
 * @method Servicosos setDescricao()     Sets the current record's "descricao" value
 * @method Servicosos setValor()         Sets the current record's "valor" value
 * @method Servicosos setCaixa()         Sets the current record's "caixa" value
 * @method Servicosos setContasreceber() Sets the current record's "contasreceber" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseServicosos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicosos');
        $this->hasColumn('numeroos', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('descricao', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '90',
             ));
        $this->hasColumn('valor', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('caixa', 'string', 18, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '18',
             ));
        $this->hasColumn('contasreceber', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '30',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}