<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Custo', 'doctrine');

/**
 * BaseCusto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descricao
 * @property string $debitocredito
 * @property string $contacontabil
 * @property string $controlecusto
 * @property integer $naoinserir
 * @property string $grupo
 * 
 * @method string  getDescricao()     Returns the current record's "descricao" value
 * @method string  getDebitocredito() Returns the current record's "debitocredito" value
 * @method string  getContacontabil() Returns the current record's "contacontabil" value
 * @method string  getControlecusto() Returns the current record's "controlecusto" value
 * @method integer getNaoinserir()    Returns the current record's "naoinserir" value
 * @method string  getGrupo()         Returns the current record's "grupo" value
 * @method Custo   setDescricao()     Sets the current record's "descricao" value
 * @method Custo   setDebitocredito() Sets the current record's "debitocredito" value
 * @method Custo   setContacontabil() Sets the current record's "contacontabil" value
 * @method Custo   setControlecusto() Sets the current record's "controlecusto" value
 * @method Custo   setNaoinserir()    Sets the current record's "naoinserir" value
 * @method Custo   setGrupo()         Sets the current record's "grupo" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCusto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('custo');
        $this->hasColumn('descricao', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '90',
             ));
        $this->hasColumn('debitocredito', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('contacontabil', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('controlecusto', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '90',
             ));
        $this->hasColumn('naoinserir', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('grupo', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '60',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}