<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Custocc', 'doctrine');

/**
 * BaseCustocc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $registro
 * @property string $custo
 * @property decimal $valor
 * 
 * @method integer getId()       Returns the current record's "id" value
 * @method integer getRegistro() Returns the current record's "registro" value
 * @method string  getCusto()    Returns the current record's "custo" value
 * @method decimal getValor()    Returns the current record's "valor" value
 * @method Custocc setId()       Sets the current record's "id" value
 * @method Custocc setRegistro() Sets the current record's "registro" value
 * @method Custocc setCusto()    Sets the current record's "custo" value
 * @method Custocc setValor()    Sets the current record's "valor" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCustocc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('custocc');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('registro', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('custo', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '90',
             ));
        $this->hasColumn('valor', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}