<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Saldocaixa', 'doctrine');

/**
 * BaseSaldocaixa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $data
 * @property decimal $saldodia
 * @property decimal $dinheiro
 * @property decimal $chequevista
 * @property decimal $chequedatado
 * @property decimal $valoroutro1
 * @property decimal $valoroutro2
 * @property string $descoutro1
 * @property string $descoutro2
 * 
 * @method integer    getId()           Returns the current record's "id" value
 * @method timestamp  getData()         Returns the current record's "data" value
 * @method decimal    getSaldodia()     Returns the current record's "saldodia" value
 * @method decimal    getDinheiro()     Returns the current record's "dinheiro" value
 * @method decimal    getChequevista()  Returns the current record's "chequevista" value
 * @method decimal    getChequedatado() Returns the current record's "chequedatado" value
 * @method decimal    getValoroutro1()  Returns the current record's "valoroutro1" value
 * @method decimal    getValoroutro2()  Returns the current record's "valoroutro2" value
 * @method string     getDescoutro1()   Returns the current record's "descoutro1" value
 * @method string     getDescoutro2()   Returns the current record's "descoutro2" value
 * @method Saldocaixa setId()           Sets the current record's "id" value
 * @method Saldocaixa setData()         Sets the current record's "data" value
 * @method Saldocaixa setSaldodia()     Sets the current record's "saldodia" value
 * @method Saldocaixa setDinheiro()     Sets the current record's "dinheiro" value
 * @method Saldocaixa setChequevista()  Sets the current record's "chequevista" value
 * @method Saldocaixa setChequedatado() Sets the current record's "chequedatado" value
 * @method Saldocaixa setValoroutro1()  Sets the current record's "valoroutro1" value
 * @method Saldocaixa setValoroutro2()  Sets the current record's "valoroutro2" value
 * @method Saldocaixa setDescoutro1()   Sets the current record's "descoutro1" value
 * @method Saldocaixa setDescoutro2()   Sets the current record's "descoutro2" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSaldocaixa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('saldocaixa');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('data', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('saldodia', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('dinheiro', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('chequevista', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('chequedatado', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('valoroutro1', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('valoroutro2', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('descoutro1', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '90',
             ));
        $this->hasColumn('descoutro2', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '90',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}