<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Indices', 'doctrine');

/**
 * BaseIndices
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $juros
 * @property decimal $multa
 * 
 * @method integer getId()    Returns the current record's "id" value
 * @method decimal getJuros() Returns the current record's "juros" value
 * @method decimal getMulta() Returns the current record's "multa" value
 * @method Indices setId()    Sets the current record's "id" value
 * @method Indices setJuros() Sets the current record's "juros" value
 * @method Indices setMulta() Sets the current record's "multa" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseIndices extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('indices');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('juros', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('multa', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}