<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Banco', 'doctrine');

/**
 * BaseBanco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $numerocc
 * @property string $titular
 * @property string $banco
 * @property string $agencia
 * @property string $chequeinicial
 * @property string $chequefinal
 * @property decimal $saldoreal
 * @property decimal $saldobancario
 * 
 * @method string  getNumerocc()      Returns the current record's "numerocc" value
 * @method string  getTitular()       Returns the current record's "titular" value
 * @method string  getBanco()         Returns the current record's "banco" value
 * @method string  getAgencia()       Returns the current record's "agencia" value
 * @method string  getChequeinicial() Returns the current record's "chequeinicial" value
 * @method string  getChequefinal()   Returns the current record's "chequefinal" value
 * @method decimal getSaldoreal()     Returns the current record's "saldoreal" value
 * @method decimal getSaldobancario() Returns the current record's "saldobancario" value
 * @method Banco   setNumerocc()      Sets the current record's "numerocc" value
 * @method Banco   setTitular()       Sets the current record's "titular" value
 * @method Banco   setBanco()         Sets the current record's "banco" value
 * @method Banco   setAgencia()       Sets the current record's "agencia" value
 * @method Banco   setChequeinicial() Sets the current record's "chequeinicial" value
 * @method Banco   setChequefinal()   Sets the current record's "chequefinal" value
 * @method Banco   setSaldoreal()     Sets the current record's "saldoreal" value
 * @method Banco   setSaldobancario() Sets the current record's "saldobancario" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBanco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banco');
        $this->hasColumn('numerocc', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '30',
             ));
        $this->hasColumn('titular', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '120',
             ));
        $this->hasColumn('banco', 'string', 105, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '105',
             ));
        $this->hasColumn('agencia', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '75',
             ));
        $this->hasColumn('chequeinicial', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '30',
             ));
        $this->hasColumn('chequefinal', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '30',
             ));
        $this->hasColumn('saldoreal', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('saldobancario', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}