<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Servicos', 'doctrine');

/**
 * BaseServicos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descricao
 * @property decimal $valor
 * @property string $controlecusto
 * 
 * @method string   getDescricao()     Returns the current record's "descricao" value
 * @method decimal  getValor()         Returns the current record's "valor" value
 * @method string   getControlecusto() Returns the current record's "controlecusto" value
 * @method Servicos setDescricao()     Sets the current record's "descricao" value
 * @method Servicos setValor()         Sets the current record's "valor" value
 * @method Servicos setControlecusto() Sets the current record's "controlecusto" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseServicos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicos');
        $this->hasColumn('descricao', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '90',
             ));
        $this->hasColumn('valor', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('controlecusto', 'string', 90, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '90',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}