<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Os', 'doctrine');

/**
 * BaseOs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $numeroos
 * @property string $numerocontrato
 * @property timestamp $dataos
 * @property string $horaos
 * @property string $observacao
 * @property integer $canalalto
 * @property integer $canalbaixo
 * @property string $tecnico
 * @property timestamp $conclusaodata
 * @property string $conclusaohora
 * @property decimal $valoros
 * @property string $tiporecebimento
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method string    getNumeroos()        Returns the current record's "numeroos" value
 * @method string    getNumerocontrato()  Returns the current record's "numerocontrato" value
 * @method timestamp getDataos()          Returns the current record's "dataos" value
 * @method string    getHoraos()          Returns the current record's "horaos" value
 * @method string    getObservacao()      Returns the current record's "observacao" value
 * @method integer   getCanalalto()       Returns the current record's "canalalto" value
 * @method integer   getCanalbaixo()      Returns the current record's "canalbaixo" value
 * @method string    getTecnico()         Returns the current record's "tecnico" value
 * @method timestamp getConclusaodata()   Returns the current record's "conclusaodata" value
 * @method string    getConclusaohora()   Returns the current record's "conclusaohora" value
 * @method decimal   getValoros()         Returns the current record's "valoros" value
 * @method string    getTiporecebimento() Returns the current record's "tiporecebimento" value
 * @method Os        setId()              Sets the current record's "id" value
 * @method Os        setNumeroos()        Sets the current record's "numeroos" value
 * @method Os        setNumerocontrato()  Sets the current record's "numerocontrato" value
 * @method Os        setDataos()          Sets the current record's "dataos" value
 * @method Os        setHoraos()          Sets the current record's "horaos" value
 * @method Os        setObservacao()      Sets the current record's "observacao" value
 * @method Os        setCanalalto()       Sets the current record's "canalalto" value
 * @method Os        setCanalbaixo()      Sets the current record's "canalbaixo" value
 * @method Os        setTecnico()         Sets the current record's "tecnico" value
 * @method Os        setConclusaodata()   Sets the current record's "conclusaodata" value
 * @method Os        setConclusaohora()   Sets the current record's "conclusaohora" value
 * @method Os        setValoros()         Sets the current record's "valoros" value
 * @method Os        setTiporecebimento() Sets the current record's "tiporecebimento" value
 * 
 * @package    test_laiguAdminTheme
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('os');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('numeroos', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('numerocontrato', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('dataos', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('horaos', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('observacao', 'string', 240, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '240',
             ));
        $this->hasColumn('canalalto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('canalbaixo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('tecnico', 'string', 105, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '105',
             ));
        $this->hasColumn('conclusaodata', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('conclusaohora', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '15',
             ));
        $this->hasColumn('valoros', 'decimal', 21, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '21',
             'scale' => ' 4',
             ));
        $this->hasColumn('tiporecebimento', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}