contaspagar:
  class: sfDoctrineRouteCollection
  options:
    model:                Contaspagar
    module:               contaspagar
    prefix_path:          /contaspagar
    column:               registro
    with_wildcard_routes: true

contasreceber:
  class: sfDoctrineRouteCollection
  options:
    model:                contasreceber
    module:               contasreceber
    prefix_path:          /contasreceber
    column:               numerodocumento
    with_wildcard_routes: true

contrato:
  class: sfDoctrineRouteCollection
  options:
    model:                contrato
    module:               contrato
    prefix_path:          /contrato
    column:               numerocontrato
    with_wildcard_routes: true

cliente:
  class: sfDoctrineRouteCollection
  options:
    model:                cliente
    module:               cliente
    prefix_path:          /cliente
    column:               codigo
    with_wildcard_routes: true

fornecedor:
  class: sfDoctrineRouteCollection
  options:
    model:                fornecedor
    module:               fornecedor
    prefix_path:          /fornecedor
    column:               codigo
    with_wildcard_routes: true

state:
  class: sfDoctrineRouteCollection
  options:
    model:                State
    module:               state
    prefix_path:          /state
    column:               id
    with_wildcard_routes: true

town:
  class: sfDoctrineRouteCollection
  options:
    model:                Town
    module:               town
    prefix_path:          /town
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: cliente, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
