<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/23 23:32:48

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=movedb',
  'username' => 'almando',
  'password' => 123456,
  'name' => 'doctrine',
)),);
