<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/20 12:55:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=dbmy0026.whservidor.com;dbname=polycanal',
  'username' => 'polycanal',
  'password' => '250325ad',
  'name' => 'doctrine',
)),);
