generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Town
    theme:                 laigu
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          town
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  
        params: { collapsed: true }
      form:    ~
      edit:    ~
      new:     ~
