generator:
  class: sfDoctrineGenerator
  param:
    model_class:           State
    theme:                 laigu
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          state
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:
        detail: 
          town:
            module: town
            params: { state_id: getId }
      new:     ~
