generator:
  class: sfDoctrineGenerator
  param:
    model_class:           fornecedor
    theme:                 laigu
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          fornecedor
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        label: [Pessoafisica: "Pessoa Fisica"]
      list:
        display: [Codigo, Nome, Cgc, Telefone]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
