generator:
  class: sfDoctrineGenerator
  param:
    model_class:           contrato
    theme:                 laigu
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contrato
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:
        detail:
          contrato:
            module: contrato
            params: { numerocontrato: getNumerocontrato }
      new:     ~
