generator:
  class: sfDoctrineGenerator
  param:
    model_class:           cliente
    theme:                 laigu
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        Nome:
          params:
            size: 260x5
        Datanascimento: {type: plain, params: date_format='dd/MM/yy'}
      list:
        title: "Pesquisa Clientes"
        display:   [Codigo, =Nome, Telefone, Transversalinicial, Transversalfinal]
        sort:      [Nome]
      filter:  ~
      form:    ~
      edit:
        title: "Editando: %%Nome%%"
        detail:
          contrato:
            module: contrato
            params: { codigocliente: getCodigo }
      new:     ~